config/routes.rb
Stocktracker::Application.routes.draw do
  root 'stocks#index'

  resources :stocks
end

app/models/stock.rb
class Stock < ActiveRecord::Base

  validates :symbol, presence: true

  scope :inverted50, -> { where( fiftyday_moving_average_inversion: true ) }
  scope :inverted200, -> { where( two_hundredday_moving_average_inversion: true ) }

  def self.inverted(amount)
    if amount == '50'
      self.inverted50
    elsif amount == '200'
      self.inverted200
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    if params[:inverted] == '50' or params[:inverted] == '200'
      @stocks = Stock.inverted(params[:inverted])
    else
      @stocks = Stock.all.limit(200)
    end
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stock }
      else
        format.html { render action: 'new' }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:name, :symbol, :sector, :price, :market_cap, :stock_exchange)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to 'Yahoo! Finance', 'http:///finance.yahoo.com'
        %li= link_to 'Google Finance', 'http:///finance.google.com'
        %li= link_to '50-day inverted', stocks_path(inverted: '50')
        %li= link_to '200-day inverted', stocks_path(inverted: '200')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Stocktracker'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Stocktracker'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container
        = render 'layouts/messages'
        = yield

app/views/stocks/_form.html.haml
= form_for @stock, html: { class: '' } do |f|
  - if @stock.errors.any?
    #error_explanation
      %h2= "#{pluralize(@stock.errors.count, "error")} prohibited this stock from being saved:"
      %ul
        - @stock.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'control-label'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :symbol, class: 'control-label'
    = f.text_field :symbol, class: 'form-control'
  .form-group
    = f.label :sector, class: 'control-label'
    = f.text_field :sector, class: 'form-control'
  .form-group
    = f.label :price, class: 'control-label'
    = f.text_field :price, class: 'form-control'
  .form-group
    = f.label :market_cap, class: 'control-label'
    = f.text_field :market_cap, class: 'form-control'
  .form-group
    = f.label :stock_exchange, class: 'control-label'
    = f.text_field :stock_exchange, class: 'form-control'
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/stocks/edit.html.haml
%h1 Editing stock

= render 'form'

= link_to 'Show', @stock
\|
= link_to 'Back', stocks_path

app/views/stocks/index.html.haml
%h1 Stocks

%table.table.table-striped.datatable#stocks-list
  %thead
    %tr
      %th Name
      %th Symbol
      %th Price
      %th Market cap (in millions)
      %th Last Trade Date
      %th 50-day Moving Average
      %th Change from 50-day Moving Average
      %th Previous Change from 50-day Moving Average
      %th 50-day Moving Average Inversion
      %th 200-day Moving Average
      %th Change from 200-day Moving Average
      %th Previous Change from 200-day Moving Average
      %th 200-day Moving Average Inversion
      %th Yahoo!

  %tbody
    - @stocks.each do |stock|
      %tr
        %td= stock.name
        %td= link_to stock.symbol, stock
        %td= stock.price
        %td= stock.market_cap
        %td= stock.last_trade_date
        %td= stock.fiftyday_moving_average
        %td= stock.change_from_fiftyday_moving_average
        %td= stock.previous_change_from_fiftyday_moving_average
        %td= stock.fiftyday_moving_average_inversion
        %td= stock.two_hundredday_moving_average
        %td= stock.change_from_two_hundredday_moving_average
        %td= stock.previous_change_from_two_hundredday_moving_average
        %td= stock.two_hundredday_moving_average_inversion
        %td= link_to 'Yahoo', "http://finance.yahoo.com/q?s=#{stock.symbol}", target: '_blank'

%br

= link_to 'New Stock', new_stock_path, class: 'btn btn-primary'

app/views/stocks/new.html.haml
%h1 New stock

= render 'form'

= link_to 'Back', stocks_path

app/views/stocks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @stock.name
%p
  %b Symbol:
  = @stock.symbol
%p
  %b Sector:
  = @stock.sector
%p
  %b Price:
  = @stock.price
%p
  %b Market cap:
  = @stock.market_cap
%p
  %b Stock exchange:
  = @stock.stock_exchange
%p
  %b Last Trade Date:
  = @stock.last_trade_date
%p
  %b Previous Last Trade Date:
  = @stock.previous_last_trade_date
%p
  %b 50-day Moving Average:
  = @stock.fiftyday_moving_average
%p
  %b Change from 50-day Moving Average:
  = @stock.change_from_fiftyday_moving_average
%p
  %b Previous Change from 50-day Moving Average:
  = @stock.previous_change_from_fiftyday_moving_average
%p
  %b 50-day Moving Average Inversion:
  = @stock.fiftyday_moving_average_inversion
%p
  %b 200-day Moving Average:
  = @stock.two_hundredday_moving_average
%p
  %b Change from 200-day Moving Average:
  = @stock.change_from_two_hundredday_moving_average
%p
  %b Previous Change from 200-day Moving Average:
  = @stock.previous_change_from_two_hundredday_moving_average
%p
  %b 200-day Moving Average Inversion:
  = @stock.two_hundredday_moving_average_inversion

= link_to 'Edit', edit_stock_path(@stock)
\|
= link_to 'Delete', @stock, :method => :delete, :data => { :confirm => 'Are you sure?' }
\|
= link_to 'Back', stocks_path